var namespaceCB =
[
    [ "Options", "namespaceCB_1_1Options.html", null ],
    [ "Sound", "namespaceCB_1_1Sound.html", null ],
    [ "Music", "namespaceCB_1_1Music.html", null ],
    [ "Particles", "namespaceCB_1_1Particles.html", null ],
    [ "Waypoint", "namespaceCB_1_1Waypoint.html", null ],
    [ "NPC", "namespaceCB_1_1NPC.html", null ],
    [ "Room", "namespaceCB_1_1Room.html", null ],
    [ "Door", "namespaceCB_1_1Door.html", null ],
    [ "TempTriggerbox", "namespaceCB_1_1TempTriggerbox.html", null ],
    [ "TempItem", "namespaceCB_1_1TempItem.html", null ],
    [ "TempDoor", "namespaceCB_1_1TempDoor.html", null ],
    [ "RoomTemplate", "namespaceCB_1_1RoomTemplate.html", null ],
    [ "TempWaypoint", "namespaceCB_1_1TempWaypoint.html", null ],
    [ "Triggerbox", "namespaceCB_1_1Triggerbox.html", null ],
    [ "Forest", "namespaceCB_1_1Forest.html", null ],
    [ "MaintenanceTunnel", "namespaceCB_1_1MaintenanceTunnel.html", null ],
    [ "Decal", "namespaceCB_1_1Decal.html", null ],
    [ "ItemTemplate", "namespaceCB_1_1ItemTemplate.html", null ],
    [ "Item", "namespaceCB_1_1Item.html", null ],
    [ "Inventory", "namespaceCB_1_1Inventory.html", null ],
    [ "Dreamfilter", "namespaceCB_1_1Dreamfilter.html", null ],
    [ "Console", "namespaceCB_1_1Console.html", "namespaceCB_1_1Console" ],
    [ "Event", "namespaceCB_1_1Event.html", [
      [ "Create", "namespaceCB_1_1Event.html#a516feb1e608fd80640c9b79d516b7bda", null ]
    ] ],
    [ "Input", "namespaceCB_1_1Input.html", null ],
    [ "Player", "namespaceCB_1_1Player.html", [
      [ "Bloodloss", "namespaceCB_1_1Player.html#a6eec4f4b57b941e3d6975ee316cc156f", null ],
      [ "CurrentRoom", "namespaceCB_1_1Player.html#ab6b180720c958fc513ac7fe9513a537b", null ],
      [ "DeathTimer", "namespaceCB_1_1Player.html#af5b798dc256a40d63012f41731a10c33", null ],
      [ "Injuries", "namespaceCB_1_1Player.html#af33496bc15124e0646807864f8027f42", null ],
      [ "Playable", "namespaceCB_1_1Player.html#acfde30e5ce6de55ce612742f801fa5f4", null ],
      [ "PlayerZone", "namespaceCB_1_1Player.html#aa59712199ef03fac02eaa92c5dbce264", null ]
    ] ],
    [ "Sound", "classCB_1_1Sound.html", null ],
    [ "Stream", "classCB_1_1Stream.html", null ],
    [ "ParticleEmitter", "classCB_1_1ParticleEmitter.html", null ],
    [ "ParticleTemplate", "classCB_1_1ParticleTemplate.html", null ],
    [ "Waypoint", "classCB_1_1Waypoint.html", null ],
    [ "NPC", "classCB_1_1NPC.html", "classCB_1_1NPC" ],
    [ "Room", "classCB_1_1Room.html", null ],
    [ "Door", "classCB_1_1Door.html", null ],
    [ "TempTriggerbox", "classCB_1_1TempTriggerbox.html", null ],
    [ "TempItem", "classCB_1_1TempItem.html", null ],
    [ "TempDoor", "classCB_1_1TempDoor.html", null ],
    [ "RoomTemplate", "classCB_1_1RoomTemplate.html", null ],
    [ "TempWaypoint", "classCB_1_1TempWaypoint.html", null ],
    [ "Triggerbox", "classCB_1_1Triggerbox.html", null ],
    [ "Forest", "classCB_1_1Forest.html", null ],
    [ "MaintenanceTunnel", "classCB_1_1MaintenanceTunnel.html", null ],
    [ "Decal", "classCB_1_1Decal.html", null ],
    [ "ItemTemplate", "classCB_1_1ItemTemplate.html", null ],
    [ "Item", "classCB_1_1Item.html", null ],
    [ "Inventory", "classCB_1_1Inventory.html", null ],
    [ "Event", "classCB_1_1Event.html", null ]
];