var searchData=
[
  ['hook_5fcombineitems_20cb_3a_3aitem_20draggeditem_20cb_3a_3aitem_20draggedontoitem_0',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @ draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @ draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md20',1,'']]],
  ['hook_5fcreatenpc_20cb_3a_3anpc_1',['void Hook_CreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md21',1,'']]],
  ['hook_5fdrawhud_2',['bool Hook_DrawHUD()',['../md_Articles_2Hooks.html#autotoc_md5',1,'']]],
  ['hook_5fdropitem_20cb_3a_3aitem_3',['bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md18',1,'']]],
  ['hook_5fexecuteconsolecommand_20string_20cmd_4',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md9',1,'']]],
  ['hook_5ffillroom_20cb_3a_3aroom_5',['bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md12',1,'']]],
  ['hook_5finitialize_6',['void Hook_Initialize()',['../md_Articles_2Hooks.html#autotoc_md1',1,'']]],
  ['hook_5finitializeevents_7',['bool Hook_InitializeEvents()',['../md_Articles_2Hooks.html#autotoc_md10',1,'']]],
  ['hook_5fkillplayer_8',['bool Hook_KillPlayer()',['../md_Articles_2Hooks.html#autotoc_md8',1,'']]],
  ['hook_5floadroomtemplateentity_20cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_9',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt; @, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt; @, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md14',1,'']]],
  ['hook_5fmouselook_10',['bool Hook_MouseLook()',['../md_Articles_2Hooks.html#autotoc_md7',1,'']]],
  ['hook_5fmoveplayer_11',['bool Hook_MovePlayer()',['../md_Articles_2Hooks.html#autotoc_md6',1,'']]],
  ['hook_5fpickitem_20cb_3a_3aitem_12',['bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md17',1,'']]],
  ['hook_5fpostcreatenpc_20cb_3a_3anpc_13',['void Hook_PostCreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md22',1,'']]],
  ['hook_5fpostfillroom_20cb_3a_3aroom_14',['void Hook_PostFillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md13',1,'']]],
  ['hook_5fremoveitem_20cb_3a_3aitem_15',['void Hook_RemoveItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md16',1,'']]],
  ['hook_5fsaveoptions_16',['void Hook_SaveOptions()',['../md_Articles_2Hooks.html#autotoc_md3',1,'']]],
  ['hook_5fselectitem_20cb_3a_3aitem_17',['void Hook_SelectItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md19',1,'']]],
  ['hook_5fshutdown_18',['void Hook_Shutdown()',['../md_Articles_2Hooks.html#autotoc_md2',1,'']]],
  ['hook_5fupdate_19',['void Hook_Update()',['../md_Articles_2Hooks.html#autotoc_md4',1,'']]],
  ['hook_5fupdateevent_20cb_3a_3aevent_20',['bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md11',1,'']]],
  ['hook_5fupdateitem_20cb_3a_3aitem_21',['bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md15',1,'']]],
  ['hook_5fupdatenpc_20cb_3a_3anpc_22',['bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt; @)',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['hooks_23',['Hooks',['../md_Articles_2Hooks.html',1,'']]]
];
