var searchData=
[
  ['camera_0',['Camera',['../classB3D_1_1Camera.html',1,'B3D']]],
  ['carray_2d1_2dg_1',['carray-1-g',['../classcarray-1-g.html',1,'']]],
  ['cb_2',['CB',['../namespaceCB.html',1,'']]],
  ['cb_3a_3aconsole_3',['Console',['../namespaceCB_1_1Console.html',1,'CB']]],
  ['cb_3a_3aconsole_3a_3amsg_4',['Msg',['../namespaceCB_1_1Console_1_1Msg.html',1,'CB::Console']]],
  ['cb_3a_3adecal_5',['Decal',['../namespaceCB_1_1Decal.html',1,'CB']]],
  ['cb_3a_3adoor_6',['Door',['../namespaceCB_1_1Door.html',1,'CB']]],
  ['cb_3a_3adreamfilter_7',['Dreamfilter',['../namespaceCB_1_1Dreamfilter.html',1,'CB']]],
  ['cb_3a_3aevent_8',['CB::Event',['../md_Articles_2Hooks.html#autotoc_md12',1,'bool Hook_UpdateEvent(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Event.html&quot; title=&quot;CB::Event&quot;&gt;CB::Event&lt;/a&gt;)'],['../namespaceCB_1_1Event.html',1,'CB.Event']]],
  ['cb_3a_3aforest_9',['Forest',['../namespaceCB_1_1Forest.html',1,'CB']]],
  ['cb_3a_3ainput_10',['Input',['../namespaceCB_1_1Input.html',1,'CB']]],
  ['cb_3a_3ainventory_11',['Inventory',['../namespaceCB_1_1Inventory.html',1,'CB']]],
  ['cb_3a_3aitem_12',['CB::Item',['../md_Articles_2Hooks.html#autotoc_md17',1,'bool Hook_CreateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md21',1,'bool Hook_DropItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md20',1,'bool Hook_PickItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md18',1,'bool Hook_UpdateItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../namespaceCB_1_1Item.html',1,'CB.Item'],['../md_Articles_2Hooks.html#autotoc_md19',1,'void Hook_RemoveItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md22',1,'void Hook_SelectItem(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt;)']]],
  ['cb_3a_3aitem_20draggeditem_20cb_3a_3aitem_20draggedontoitem_13',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['cb_3a_3aitem_20draggedontoitem_14',['void Hook_CombineItems(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedItem, &lt;a class=&quot;el&quot; href=&quot;classCB_1_1Item.html&quot; title=&quot;CB::Item&quot;&gt;CB::Item&lt;/a&gt; draggedOntoItem)',['../md_Articles_2Hooks.html#autotoc_md23',1,'']]],
  ['cb_3a_3aitemtemplate_15',['ItemTemplate',['../namespaceCB_1_1ItemTemplate.html',1,'CB']]],
  ['cb_3a_3amaintenancetunnel_16',['MaintenanceTunnel',['../namespaceCB_1_1MaintenanceTunnel.html',1,'CB']]],
  ['cb_3a_3amap_17',['Map',['../namespaceCB_1_1Map.html',1,'CB']]],
  ['cb_3a_3amenu_18',['Menu',['../namespaceCB_1_1Menu.html',1,'CB']]],
  ['cb_3a_3amusic_19',['Music',['../namespaceCB_1_1Music.html',1,'CB']]],
  ['cb_3a_3anpc_20',['CB::NPC',['../md_Articles_2Hooks.html#autotoc_md34',1,'bool Hook_DisableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md33',1,'bool Hook_EnableNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md26',1,'bool Hook_RemoveNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md27',1,'bool Hook_UpdateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../namespaceCB_1_1NPC.html',1,'CB.NPC'],['../md_Articles_2Hooks.html#autotoc_md24',1,'void Hook_CreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)'],['../md_Articles_2Hooks.html#autotoc_md25',1,'void Hook_PostCreateNPC(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1NPC.html&quot; title=&quot;CB::NPC&quot;&gt;CB::NPC&lt;/a&gt;)']]],
  ['cb_3a_3anpc_3a_3atype_20hook_5fconsolenpcnametotype_20string_20name_21',['CB::NPC::Type Hook_ConsoleNPCNameToType(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; name)',['../md_Articles_2Hooks.html#autotoc_md28',1,'']]],
  ['cb_3a_3anpc_3a_3atype_20type_22',['CB::NPC::Type type',['../md_Articles_2Hooks.html#autotoc_md31',1,'int Hook_ConsoleCheckCanChangeNPCSpeed(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md32',1,'int Hook_ConsoleCheckCanToggleNPC(CB::NPC::Type type)'],['../md_Articles_2Hooks.html#autotoc_md30',1,'int Hook_ConsoleSpawnNPC(CB::NPC::Type type)']]],
  ['cb_3a_3anpc_3a_3atype_20type_20bool_20isplural_23',['string Hook_ConsoleNPCTypeToName(CB::NPC::Type type, bool isPlural)',['../md_Articles_2Hooks.html#autotoc_md29',1,'']]],
  ['cb_3a_3aoptions_24',['Options',['../namespaceCB_1_1Options.html',1,'CB']]],
  ['cb_3a_3aparticles_25',['Particles',['../namespaceCB_1_1Particles.html',1,'CB']]],
  ['cb_3a_3aplayer_26',['Player',['../namespaceCB_1_1Player.html',1,'CB']]],
  ['cb_3a_3aqueuedsubtitlemsg_27',['QueuedSubtitleMsg',['../namespaceCB_1_1QueuedSubtitleMsg.html',1,'CB']]],
  ['cb_3a_3aroom_28',['CB::Room',['../md_Articles_2Hooks.html#autotoc_md13',1,'bool Hook_FillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)'],['../namespaceCB_1_1Room.html',1,'CB.Room'],['../md_Articles_2Hooks.html#autotoc_md14',1,'void Hook_PostFillRoom(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1Room.html&quot; title=&quot;CB::Room&quot;&gt;CB::Room&lt;/a&gt;)']]],
  ['cb_3a_3aroomtemplate_29',['RoomTemplate',['../namespaceCB_1_1RoomTemplate.html',1,'CB']]],
  ['cb_3a_3aroomtemplate_20int_20rmeshversion_20b3d_3a_3astream_20string_20entityname_30',['bool Hook_LoadRoomTemplateEntity(&lt;a class=&quot;el&quot; href=&quot;classCB_1_1RoomTemplate.html&quot; title=&quot;CB::RoomTemplate&quot;&gt;CB::RoomTemplate&lt;/a&gt;, int rMeshVersion, &lt;a class=&quot;el&quot; href=&quot;classB3D_1_1Stream.html&quot; title=&quot;B3D::Stream&quot;&gt;B3D::Stream&lt;/a&gt;, &lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; entityName)',['../md_Articles_2Hooks.html#autotoc_md15',1,'']]],
  ['cb_3a_3asound_31',['Sound',['../namespaceCB_1_1Sound.html',1,'CB']]],
  ['cb_3a_3asubtitlebox_32',['SubtitleBox',['../namespaceCB_1_1SubtitleBox.html',1,'CB']]],
  ['cb_3a_3asubtitlecolor_33',['SubtitleColor',['../namespaceCB_1_1SubtitleColor.html',1,'CB']]],
  ['cb_3a_3asubtitleentry_34',['SubtitleEntry',['../namespaceCB_1_1SubtitleEntry.html',1,'CB']]],
  ['cb_3a_3asubtitlemsg_35',['SubtitleMsg',['../namespaceCB_1_1SubtitleMsg.html',1,'CB']]],
  ['cb_3a_3asubtitles_36',['Subtitles',['../namespaceCB_1_1Subtitles.html',1,'CB']]],
  ['cb_3a_3asubtitletoken_37',['SubtitleToken',['../namespaceCB_1_1SubtitleToken.html',1,'CB']]],
  ['cb_3a_3atempdoor_38',['TempDoor',['../namespaceCB_1_1TempDoor.html',1,'CB']]],
  ['cb_3a_3atempitem_39',['TempItem',['../namespaceCB_1_1TempItem.html',1,'CB']]],
  ['cb_3a_3atemptriggerbox_40',['TempTriggerbox',['../namespaceCB_1_1TempTriggerbox.html',1,'CB']]],
  ['cb_3a_3atempwaypoint_41',['TempWaypoint',['../namespaceCB_1_1TempWaypoint.html',1,'CB']]],
  ['cb_3a_3atriggerbox_42',['Triggerbox',['../namespaceCB_1_1Triggerbox.html',1,'CB']]],
  ['cb_3a_3awaypoint_43',['Waypoint',['../namespaceCB_1_1Waypoint.html',1,'CB']]],
  ['channel_44',['Channel',['../classB3D_1_1Channel.html',1,'B3D']]],
  ['cmd_45',['bool Hook_ExecuteConsoleCommand(&lt;a class=&quot;el&quot; href=&quot;classstring.html&quot; title=&quot;string&quot;&gt;string&lt;/a&gt; cmd)',['../md_Articles_2Hooks.html#autotoc_md9',1,'']]],
  ['create_46',['Create',['../namespaceCB_1_1Event.html#a516feb1e608fd80640c9b79d516b7bda',1,'CB::Event']]],
  ['createmessage_47',['CreateMessage',['../namespaceCB_1_1Console.html#ac85ce1c9e2b34f03d873594300e252a1',1,'CB::Console']]],
  ['cstr_48',['cstr',['../classcstr.html',1,'']]],
  ['current096_49',['Current096',['../classCB_1_1NPC.html#a15bfa4204bdb382ff5ac38ee879958a4',1,'CB::NPC']]],
  ['current106_50',['Current106',['../classCB_1_1NPC.html#a60f67757f176405122f108a7c02f4d9e',1,'CB::NPC']]],
  ['current173_51',['Current173',['../classCB_1_1NPC.html#afaa32cd320b6bcc5c1269fe4f1bcaa6d',1,'CB::NPC']]],
  ['current5131_52',['Current5131',['../classCB_1_1NPC.html#a781cd1d69dfa817bfc6535bc6747a04b',1,'CB::NPC']]],
  ['currentroom_53',['CurrentRoom',['../namespaceCB_1_1Player.html#ab6b180720c958fc513ac7fe9513a537b',1,'CB::Player']]]
];
